### PR TITLE
Fix Issue #299

### LINKED ISSUE #299: Aggregation adds aggregated value with timestamp = 0 to previous time bucket
```
127.0.0.1:6379> TS.RANGE a 0 -1
1) 1) (integer) 0
   2) "1"
2) 1) (integer) 5
   2) "0"
3) 1) (integer) 17
   2) "4"
4) 1) (integer) 18
   2) "3"
5) 1) (integer) 22
   2) "7"
127.0.0.1:6379> TS.RANGE a 0 -1 aggregation sum 10
1) 1) (integer) 10
   2) "8"
2) 1) (integer) 20
   2) "7"
127.0.0.1:6379> TS.RANGE a 0 -1 aggregation avg 10
1) 1) (integer) 10
   2) "2"
2) 1) (integer) 20
   2) "7"
```
Should have been 
```
127.0.0.1:6379> TS.RANGE a 0 -1 aggregation sum 10
1) 1) (integer) 0
   2) "1"
2) 1) (integer) 10
   2) "7"
3) 1) (integer) 20
   2) "7"
127.0.0.1:6379> TS.RANGE a 0 -1 aggregation avg 10
1) 1) (integer) 0
   2) "0.5"
2) 1) (integer) 10
   2) "3.5"
3) 1) (integer) 20
   2) "7"
```

### PR DESCRIPTION
**Pull request by ashtul**
fix #299 
I need this for #292

### CODE REVIEW

**Comment by K-Jo** [comment]
@ashtul make sure to cherry-pick this on the 1.2 branch after it's done

File: src/module.c [hunk 1]
```diff
@@ -519,9 +519,13 @@ int ReplySeriesRange(RedisModuleCtx *ctx, Series *series, api_timestamp_t start_
...
         context = aggObject->createContext();
-    
+        // setting the first timestamp of the aggregation
+        timestamp_t initTS = series->funcs->GetFirstTimestamp(iterator.currentChunk);
+        last_agg_timestamp = initTS - (initTS % time_delta);
+    }
+
     RedisModule_ReplyWithArray(ctx, REDISMODULE_POSTPONED_ARRAY_LEN);
     while (SeriesIteratorGetNext(&iterator, &sample) != 0 &&
                     (maxResults == -1 || arraylen < maxResults)) {
```
Comment (rafie) [inline src/module.c]: Move 'if (aggObject' outside of loop.
