### PR TITLE
Protect from overflow of bit when >=64

### LINKED ISSUE #358: Wrong double value in ts.range
Per [discussion in Google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/redistimeseries/wH0R69e8lOs)

### PR DESCRIPTION
**Pull request by ashtul**
Fix issue where in rare cases float is taking 64 bits which align with `uint64`.
Shifting `1 << 64` then has caused disruption in all following values.

fix #358

### CODE REVIEW

File: src/gorilla.c [hunk 1]
```diff
@@ -115,17 +115,19 @@
 
 // 2^bit
 static inline u_int64_t BIT(u_int64_t bit) {
-    return 1ULL << bit;
+    __uint128_t tmp = 1;
```
Comment (danni-m) [inline src/gorilla.c]: @ashtul can we add unit tests to these functions?

Comment (ashtul) [reply src/gorilla.c]: @danni-m 
We defiantly should.
We need to discuss the platform for all unit tests.
