### PR TITLE
Fixed duplicate policy min/max rules not working for negative values

### LINKED ISSUE #588: ON_DUPLICATE min/max rules not working for negative values
HI, I input these commands. Is the result correct?

```
127.0.0.1:6379[10]> ts.create test1 DUPLICATE_POLICY min
OK
127.0.0.1:6379[10]> ts.add test1 1 -0.05 ON_DUPLICATE min
(integer) 1
127.0.0.1:6379[10]> ts.range test1 - +
1) 1) (integer) 1
   2) -0.05
127.0.0.1:6379[10]> ts.add test1 1 -0.06 ON_DUPLICATE min
(integer) 1
127.0.0.1:6379[10]> ts.range test1 - +
1) 1) (integer) 1
   2) 0
127.0.0.1:6379[10]> ts.add test1 1 -100 ON_DUPLICATE min
(integer) 1
127.0.0.1:6379[10]> ts.range test1 - +
1) 1) (integer) 1
   2) 0
----
127.0.0.1:6379[10]> ts.info test1 debug
 1) totalSamples
 2) (integer) 1
 3) memoryUsage
 4) (integer) 4184
 5) firstTimestamp
 6) (integer) 1
 7) lastTimestamp
 8) (integer) 1
 9) retentionTime
10) (integer) 0
11) chunkCount
12) (integer) 1
13) chunkSize
14) (integer) 4096
15) chunkType
16) compressed
17) duplicatePolicy
18) min
19) labels
20) (empty list or set)
21) sourceKey
22) (nil)
23) rules
24) (empty list or set)
25) Chunks
26) 1)  1) startTimestamp
        2) (integer) 1
        3) endTimestamp
        4) (integer) 1
        5) samples
        6) (integer) 1
        7) size
        8) (integer) 4096
        9) bytesPerSample
       10) "4096"

```

--
redis info:
...
# Modules
module:name=timeseries,ver=10406,api=1,filters=0,usedby=[],using=[],options=[]

### LINKED ISSUE #591: CI failing unit tests not failing build
If we check the following CI output we see that one of the unit tests is failing ( as expected ) and not failing the build 
https://app.circleci.com/pipelines/github/RedisTimeSeries/RedisTimeSeries/2075/workflows/d1333f16-0313-44fa-961d-ad752f5c4034/jobs/5284

### PR DESCRIPTION
**Pull request by filipecosta90**
- [add] Added test_Uncompressed_Uncompressed_UpsertSample_DuplicatePolicy to mimic issue #588
- Fixes #588 by doing the proper double comparison ( PS: simplified further the comparison @danni-m )
- Fixes #591 by using the number of failed unit tests as the unit wrapper return code

### CODE REVIEW

File: src/generic_chunk.c [hunk 1]
```diff
@@ -69,13 +69,15 @@ ChunkResult handleDuplicateSample(DuplicatePolicy policy, Sample oldSample, Samp
...
+                newSample->value = oldSample.value;
             return CR_OK;
         case DP_MAX:
-            newSample->value = max(oldSample.value, newSample->value);
+            if (oldSample.value > newSample->value)
+                newSample->value = oldSample.value;
             return CR_OK;
         case DP_SUM:
-            newSample->value = oldSample.value + newSample->value;
+            newSample->value += (oldSample.value);
```
Comment (danni-m) [inline src/generic_chunk.c:80]: @filipecosta90 why the extra parentheses?

File: src/generic_chunk.c [hunk 2]
```diff
@@ -69,13 +69,15 @@ ChunkResult handleDuplicateSample(DuplicatePolicy policy, Sample oldSample, Samp
         case DP_LAST:
             return CR_OK;
         case DP_MIN:
-            newSample->value = min(oldSample.value, newSample->value);
+            if (oldSample.value < newSample->value)
+                newSample->value = oldSample.value;
```
Comment (danni-m) [inline src/generic_chunk.c:73]: in the past we had a max/min macro that did exactly this. but this is good enough as well.

**Review by danni-m — APPROVED** [review]

File: src/generic_chunk.c (hunk 2 above)
Comment (filipecosta90) [reply src/generic_chunk.c:73]: @danni-m did not used the macro to save unnecessary work when the conditions are not met ( meaning newSample does not need to be updated right ).

File: src/generic_chunk.c (hunk 1 above)
Comment (filipecosta90) [reply src/generic_chunk.c:80]: temporary aesthetics and then forgot to remove them :). fixing

**Review by danni-m — APPROVED** [review]
