### PR TITLE
fix issue 373

### LINKED ISSUE #373: Crash on incomplete TS.RANGE query due to parseCountArgument
Hi, guys,

will somebody please confirm a crash for me? I pressed Enter too soon today on some queries and finally got this repeatable crash:
```
docker run -p 6379:6379 -it --rm redislabs/redistimeseries
redis-cli
ts.create s1:0:0 retention 2592000 
ts.range s1:0:0 - + count 
```
If not confirmed, I'll append the logs.

Thanks!

### PR DESCRIPTION
**Pull request by ashtul**
fix #373

### CODE REVIEW

File: src/module.c [hunk 1]
```diff
@@ -203,6 +203,10 @@ static int parseRangeArguments(RedisModuleCtx *ctx, Series *series, int start_in
 static int parseCountArgument(RedisModuleCtx *ctx, RedisModuleString **argv, int argc, long long *count) {
     int offset = RMUtil_ArgIndex("COUNT", argv, argc);
     if (offset > 0) {
+        if (offset + 1 == argc) {
+            RedisModule_ReplyWithError(ctx, "TSDB: COUNT argument is missing");
```
Comment (filipecosta90) [inline src/module.c:207]: @ashtul should we be this specific, or use the wrong arity one?

Comment (ashtul) [reply src/module.c:207]: @filipecosta90 we use explicit language quite often to help users understand their error.

Comment (danni-m) [reply src/module.c:207]: @filipecosta90 I agree that wrong arity is more "accurate" error, but its not like RESP has specific error code. I do like the more explicitness since our commands are getting more and more complex and harder to debug when theres error.

Comment (filipecosta90) [reply src/module.c:207]: agree. lets unblock this review (since it fixes an crash) and merge :+1:
